graph TD
    classDef inicioFin fill:#B8B8B8,stroke:#000000,stroke-width:2px,color:#000000,font-weight:bold;
    classDef predicado fill:#FFF9C4,stroke:#000000,stroke-width:2px,color:#000000,font-weight:bold;
    1((1))
    2((2))
    3((3))
    4((4))
    5((5))
    6((6))
    class 1,6 inicioFin;
    class 2,3,4,5 predicado;
    1 -->|e1: Entrada| 2
    2 -->|e2: True| 6
    2 -->|e3: False| 3
    3 -->|e4: True| 6
    3 -->|e5: False| 4
    4 -->|e6: True| 6
    4 -->|e7: False| 5
    5 -->|e8: True| 6
    5 -->|e9: False| 6
    linkStyle default stroke:#000000,stroke-width:2px,font-family:Arial;
